name: CI

on:
  push:
    branches: [ develop, master, 'feature/**' ]
  pull_request:
    branches: [ develop, master ]

jobs:
  backend:
    name: Backend - Lint, Build & Test
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: Install dependencies
        run: npm install
      - name: Lint (à compléter)
        run: echo "Pas de script lint défini pour le backend"
      - name: Build
        run: npm run build
      - name: Test
        run: |
          if [ "$(npm run | grep 'test' | wc -l)" -gt 0 ]; then
            npm test || true
          else
            echo "Aucun script de test défini"
          fi

  frontend:
    name: Frontend - Lint, Build & Test
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: Install dependencies
        run: npm install
      - name: Lint
        run: npm run lint
      - name: Build
        run: npm run build
      - name: Test
        run: |
          if [ "$(npm run | grep 'test' | wc -l)" -gt 0 ]; then
            npm test || true
          else
            echo "Aucun script de test défini"
          fi 